### PR TITLE
FEAT: do not throw error if previous release was not found

### PR DESCRIPTION
**Pull request by rreckonerr**
Since I found no way to add a test for it I'd like to check out if it actually works before merging this. I will let you know if this PR prevents the build pipeline from failing in case a release commit wasn't found.

Closes https://github.com/Exelord/ember-cli-deploy-sentry-cli/issues/10

### CODE REVIEW

**Review by Exelord — APPROVED** [review]
On your mark!😎

**Comment by rreckonerr** [comment]
@Exelord 
Something strange is going on, it seems like sentry-cli doesn't expect multiple flags to be set. First, it created a release `"--ignore-missing"`, then threw an error that ignore-missing is not an argument when I moved flags to the end of the command. I suspect that it expects `--auto` OR `--ignore-missing` flags to be passed. I will ask around in sentry-cli repo and get back to you 🥲

**Comment by rreckonerr** [comment]
@Exelord I think I figured out what's going on here. Seems like the problem is about the order of passed flags vs actual release version.

So if "set-commits --active --ignore-missing <RELEASE>" flags are passed before the release version, the second argument (in our case `--ignore-missing`) will be treated as a release version and release named `"--ignore-missing"` will be created, and we'll publish another release with proper name from the `didDeploy` hook. In that case all assosiated commits will stay in "--ignore-missing" release and the proper release will have no assosiated commits 🤦‍♂️

I've moved the flags after the release version and now it seems to work as expected, also I've opened a [new issue in the sentry-cli repo](https://github.com/getsentry/sentry-cli/issues/964).

I think it's still safe to go with the workaround of moving flags to after the release version, but before actually merging this I'd like some one else to test this version too 🙂

**Review by Exelord — APPROVED** [review]

**Comment by Exelord** [comment]
I think we are good :)

**Comment by Exelord** [comment]
@rreckonerr how's the testing going? :)

**Comment by rreckonerr** [comment]
Thanks, @Exelord 🎉🎉🎉

**Comment by urbany** [comment]
@Exelord hi, first of all thanks for the plugin would you accept a PR to also add `--ignore-empty` to this command?

**Comment by Exelord** [comment]
Hey @urbany :) Could you briefly explain what it does?

**Comment by urbany** [comment]
I think it's because I don't have sentry integrated with my repository, this is what is written in the docs:

> Dealing With Missing Commits
> There are scenarios in which your repositories may be missing commits previously used in the release. This can happen whenever you modify the commit in question by, for example, amending it, rebasing, or squashing multiple commits together. In this case, Sentry CLI will be unable to find it, and will throw an error that the commit cannot be found.
> 
> When this happens, you can pass an additional --ignore-missing flag. This will allow the command to fall back to the default behavior, which is creating a release with a specified number of commits (see the section above).
https://docs.sentry.io/product/cli/releases/#dealing-with-missing-commits

Basically it does not error if the commit is not found.

**Pull request merged**
